### ISSUE TITLE
Automate docs build

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/rcs#16]
Ideally fully automate the generation and publishing of sphinx docs.  If the publishing is annoying at least get to a point where a single script can build and publish.

DanB: I'd like to add a few sub-tasks for docs that need updating:

* [ ] docs/admin/connecting-to-ramp.rst
* [ ] docs/services/contract_10.rst (new, from the old v1 contract)
* [ ] docs/services/contract.rst (Big one!)
* [ ] docs/services/jsonschema.rst
* [ ] docs/services/quickref.rst
* [ ] docs/services/signing.rst (Quick update to change v1 to v2, otherwise stays the same)

**Comment by dan-bowerman** [comment]
All docs are updated to v2 specifications, and complete. Auto-build is working. 

A new potential spin-off task (which will involve conversation with @alyec and @AleksueiR on best approach to handle this) will be to separate the current RCS documents website at http://fgpv-vpgf.github.io/rcs/ into v1 and v2 sections.
