### ISSUE TITLE
Usage of proxy to fetch service definition for both upgrade and registration endpoints

### ISSUE THREAD

**Issue by jsmoreau** [fgpv-vpgf/rcs#32]
RCS v1 would use a config property (FEATURE_SERVICE_PROXY) to fetch feature service definitions. This would allow RCS to work in dev and tst environnements that have limited access to the internet. RCS v2 does not make use of the proxy. This would be needed for both upgrading existing entries as well as registering new ones.

**Comment by dan-bowerman** [comment]
Completed and included in RC3.
