### ISSUE TITLE
Provide a List of Keys and Service Endpoints

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/rcs#33]
Allow a developer to interrogate the RCS to provide a list of registered items for testing purposes.  RCS should return a list of Keys currently registered in the system as well as the Service Endpoint URL bound to the key.

**Comment by alyec** [comment]
Some clarifications based on discussions in gitter.

We have two use cases for this endpoint:
- get a bunch of keys for debugging
- test services directly (i.e. without the viewer) to see how they render in other viewers (e.g. AGOL)

Proposed endpoint: `/v2/all_keys/[lang]`

Response:
```js
[
  {"key":"42","url":"http://example.com/blue_polygons"},
  {"key":"243","url":"http://another.example.com/wind_arrows"}
]
```

The service should only be enabled in debug mode.

**Comment by dan-bowerman** [comment]
Completed and included in RC3.
