### ISSUE TITLE
Parse and identify queryable WMS layers

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/rcs#47]
Following Gitter conversation @ https://gitter.im/fgpv-vpgf?at=57741239bb1de91c54a9dc51

When registering a WMS, add a check for whether the layer is queryable. This will be used by RAMP to determine whether the identify tool should work with a displayed layer.

**Comment by dan-bowerman** [comment]
@mweech @alyec @james-rae 
In an example such as registering http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?VERSION=1.1.1&request=GetCapabilities&service=wms with the recursive flag set, we can only set "queryable" on the whole registration, not each layer underneath under the existing schema. How should we handle this if a service has multiple layers, some queryable, some not?

**Comment by dan-bowerman** [comment]
:point_up: applies to scrape_only registrations as well.

**Comment by mweech** [comment]
we are going to have to update the schema to allow for this IMO.  the question is, how much of an impact on the viewer by adding these values? if anything it sounds like the kind of thing that would enable more fine grained option setting.
