### ISSUE TITLE
Create new Update Endpoint

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/rcs#9]
Replace existing simplification factor endpoint to a more general update feature.  Would allow for individual records to have specific attributes updated.

**Comment by alyec** [comment]
This probably won't happen during this iteration, so moving it preemptively.

**Comment by dan-bowerman** [comment]
Out of curiosity, is there background or a use-case for creating this update endpoint? I could see it being beneficial to someone doing manual entries or updates to an RCS instance, but from a Catalogue integration perspective I assume they would just re-register the entire layer/service.

**Comment by alyec** [comment]
The initial use case was for simplification factor (i.e. being able to set simplification factor without having to fully construct a new registration record).  I don't know if this use case still exists, but if it does a general update endpoint is probably better than a simplification factor specific one.

I'm fairly certain simplification factor doesn't work in v2.

**Comment by dan-bowerman** [comment]
Agreed, that would be a compelling use-case with R1 for updating a record for performance tweaking. I believe you're right that this is not present in v2 registration or the R2 viewer for that matter. @mweech, any thoughts?
